name = "miniapp-scafolding"
compatibility_date = "2023-10-07"

# For Cloudflare Workers
main = "worker/index.ts"

[[d1_databases]]
binding = "D1_DATABASE"
database_name = "telegram-calendar"
database_id = "362bb840-81ef-4244-87b2-d40af0942d1d"
