name = "telegram-calendar"
pages_build_output_dir = "./dist"
main = "index.js"
compatibility_date = "2023-10-07"

[[d1_databases]]
binding = "DB"
database_name = "telegram-calendar"
database_id = "18d4bb4d-0fa2-4753-927b-5d820701e1db"
